# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171125_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesel', models.CharField(max_length=11)),
                ('first_name', models.CharField(max_length=40)),
                ('second_name', models.CharField(blank=True, max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('instructor_rank', models.CharField(blank=True, choices=[('pwd', 'pwd.'), ('phm', 'phm.'), ('hm', 'hm.')], max_length=3)),
                ('which_service', models.IntegerField()),
                ('service_type', models.CharField(choices=[('lit', 'Liturgiczno-reprezentacyjna'), ('med', 'Medyczna'), ('wew', 'Wewnętrzna'), ('szt', 'Sztab'), ('tv', 'Medialna'), ('cln', 'Porządkowa')], max_length=3)),
                ('rescue_course', models.CharField(blank=True, max_length=255)),
                ('which_rescue_service', models.IntegerField(null=True)),
                ('rescue_certificate', models.FileField(blank=True, upload_to='rescue_certificates/')),
                ('leader', models.BooleanField()),
                ('leader_email', models.EmailField(max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatrolList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('hufiec', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Bucketlist',
        ),
        migrations.AddField(
            model_name='participantlist',
            name='patrol_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PatrolList'),
        ),
    ]
