# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171126_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantlist',
            old_name='patrol_id',
            new_name='patrol',
        ),
    ]
