# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171127_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantlist',
            name='rescue_certificate',
            field=models.URLField(blank=True),
        ),
    ]
