# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171128_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantlist',
            name='leader_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
